### ISSUE TITLE
Reproducing Results

### ISSUE THREAD

**Issue by tangjialiang97** [Kowsher/LLMMixer#4]
I encountered some issues while attempting to reproduce the results presented in the paper. I used the code and parameter settings provided in the public repository, but the results I obtained differ significantly from those reported in your paper. I would like to seek your guidance in understanding any potential reasons for this discrepancy and any specific settings or adjustments that might help me achieve comparable results

Reproduce results:
| Seq_len | Pred_len | Data  | Mse    | Mae    |
| ------- | -------- | ----- | ------ | ------ |
| 96      | 96       | ETTh1 | 0.3935 | 0.412  |
| 96      | 192      | ETTh1 | 0.4578 | 0.4441 |
| 96      | 384      | ETTh1 | 0.4998 | 0.4618 |
| 96      | 720      | ETTh1 | 0.4974 | 0.4722 |
|         |          | Mean  | 0.4621 | 0.4475 |

Training setting:
model_name=LLMMixer

seq_len=96
e_layers=2
down_sampling_layers=3
down_sampling_window=2
learning_rate=0.0001
d_model=16
d_ff=32
train_epochs=20
patience=100
batch_size=128
learning_rate=0.001
pred_len=96
{
  python3 run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path  /hss/giil/temp/data/all_six_datasets/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_$seq_len'_'96 \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len $seq_len \
  --label_len 0 \
  --pred_len 96 \
  --e_layers $e_layers \
  --enc_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --d_model $d_model \
  --d_ff $d_ff \
  --learning_rate $learning_rate \
  --train_epochs $train_epochs \
  --patience $patience \
  --batch_size $batch_size \
  --learning_rate $learning_rate \
  --down_sampling_layers $down_sampling_layers \
  --down_sampling_method avg \
  --down_sampling_window $down_sampling_window
}
sleep 1
wait
{
  python3 run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path  /hss/giil/temp/data/all_six_datasets/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_$seq_len'_'192 \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len $seq_len \
  --label_len 0 \
  --pred_len 192 \
  --e_layers $e_layers \
  --enc_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --d_model $d_model \
  --d_ff $d_ff \
  --learning_rate $learning_rate \
  --train_epochs $train_epochs \
  --patience $patience \
  --batch_size $batch_size \
  --learning_rate $learning_rate \
  --down_sampling_layers $down_sampling_layers \
  --down_sampling_method avg \
  --down_sampling_window $down_sampling_window
}
sleep 1
wait
{
  python3 run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path  /hss/giil/temp/data/all_six_datasets/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_$seq_len'_'384 \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len $seq_len \
  --label_len 0 \
  --pred_len 384 \
  --e_layers $e_layers \
  --enc_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --d_model $d_model \
  --d_ff $d_ff \
  --learning_rate $learning_rate \
  --train_epochs $train_epochs \
  --patience $patience \
  --batch_size $batch_size \
  --learning_rate $learning_rate \
  --down_sampling_layers $down_sampling_layers \
  --down_sampling_method avg \
  --down_sampling_window $down_sampling_window
}
sleep 1
wait
{
  python3 run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path  /hss/giil/temp/data/all_six_datasets/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_$seq_len'_'720 \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len $seq_len \
  --label_len 0 \
  --pred_len 720 \
  --e_layers $e_layers \
  --enc_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --d_model $d_model \
  --d_ff $d_ff \
  --learning_rate $learning_rate \
  --train_epochs $train_epochs \
  --patience $patience \
  --batch_size $batch_size \
  --learning_rate $learning_rate \
  --down_sampling_layers $down_sampling_layers \
  --down_sampling_method avg \
  --down_sampling_window $down_sampling_window
}
sleep 1
wait

**Comment by tangjialiang97** [comment]
We further conduct experiments on ETTh2 dataset and the LLM is RoBERTa-base. However, the results are still inconsistent with those reported in the paper.
| Seq_len | Pred_len | Data                  | Mse    | Mae    |
| ------- | -------- | --------------------- | ------ | ------ |
| 96      | 96       | ETTh2                 | 0.3143 | 0.3612 |
| 96      | 192      | ETTh2                 | 0.39   | 0.4062 |
| 96      | 384      | ETTh2                 | 0.4157 | 0.4326 |
| 96      | 720      | ETTh2                 | 0.4311 | 0.4456 |
|         |          | Mean                  | 0.3877 | 0.4114 |
|         |          | Reported in the paper | 0.349  | 0.395 |

**Comment by Kowsher** [comment]
I just ran ETTh1 for 196 and achieved the following results:

MSE: 0.4198439121246338
MAE: 0.4268854558467865
These results are even better than those reported in our paper ( 0.439, 0.470). Please note that the results in the paper were obtained using an H100 GPU. I believe that adjusting the hyperparameters could potentially yield even better outcomes.

For your reference, I have uploaded the notebook I used for this run. It includes details about the GPU I used in this test (RTX 3090).


https://github.com/Kowsher/LLMMixer/blob/main/notebook.ipynb
